services:
  config-server:
    build: ./config-server
    container_name: fundquest-config-server
    environment:
      # Azure OAuth Configuration
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_REDIRECT_URI: ${AZURE_REDIRECT_URI:-http://localhost:3000/auth/callbacks}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET}

      # External Database Configuration
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}

      # CORS Configuration
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000}
    ports:
      - "8888:8888"
    networks:
      - fundquest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  eureka-server:
    build: ./eureka-server
    container_name: fundquest-eureka-server
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    networks:
      - fundquest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  auth-service:
    build: ./auth-service
    container_name: fundquest-auth-service
    ports:
      - "8010:8010"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    networks:
      - fundquest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  api-gateway:
    build: ./api-gateway
    container_name: fundquest-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    networks:
      - fundquest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  fundquest-network:
    driver: bridge