spring:
  application:
    name: auth-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

azure:
  client-id: db541a76-dee1-42a8-8551-0336af1d250c
  client-secret:
  tenant-id: ac899a80-3bdc-43fd-8ffc-3a25b13612c3
  redirect-uri: http://localhost:3000/auth/callbacks

jwt:
  secret: oInSIJCVHgXa7xXDQD+hqDAR4aLcpsOxV3eadpmPEWkilp6jfsbfZRF1N5DLNV6w
  expiration: 3600000  # 1 hour in milliseconds



