version: '3.8'

services:

  postgres:
    image: postgres:17-alpine
    container_name: fundquest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fundquest_auth
      POSTGRES_USER: fundquest_user
      POSTGRES_PASSWORD: fundquest_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fundquest-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fundquest_user -d fundquest_auth"]
      interval: 30s
      timeout: 10s
      retries: 5

  # FundQuest Auth Service
  auth-service:
    image: fundquest/auth-service:latest
    container_name: fundquest-auth-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Server Configuration
      SERVER_PORT: 8080
      SERVER_CONTEXT_PATH: /api
      #SPRING_PROFILES_ACTIVE: production

      # Database Configuration
      DATABASE_URL: jdbc:postgresql://postgres:5432/fundquest_auth
      DATABASE_USERNAME: fundquest_user
      DATABASE_PASSWORD: fundquest_password
      DB_POOL_SIZE: 10
      DB_POOL_MIN_IDLE: 2
      DB_CONNECTION_TIMEOUT: 30000
      DB_IDLE_TIMEOUT: 600000
      DB_MAX_LIFETIME: 1800000

      # JPA Configuration
      JPA_DDL_AUTO: validate
      JPA_SHOW_SQL: false
      JPA_FORMAT_SQL: false

      # Flyway Configuration
      FLYWAY_ENABLED: true
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_VALIDATE_ON_MIGRATE: true

      # Microsoft OAuth2 Configuration (Replace with your actual values)
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID:-your-client-id}
      MICROSOFT_TENANT_ID: ${MICROSOFT_TENANT_ID:-your-tenant-id}

      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-YourSecretKeyHere_PleaseUpdateThis_MustBe256BitsOrLonger_ForHS256Algorithm}
      JWT_ACCESS_TOKEN_EXPIRATION: ${JWT_ACCESS_TOKEN_EXPIRATION:-900000}
      JWT_REFRESH_TOKEN_EXPIRATION: ${JWT_REFRESH_TOKEN_EXPIRATION:-604800000}

      # Application Configuration
      APP_NAME: FundQuest Auth Service
      APP_VERSION: 1.0.0
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,https://yourdomain.com}
      COOKIE_SECURE: true
      COOKIE_SAME_SITE: Lax

      # Logging Configuration
      LOG_LEVEL_APP: INFO
      LOG_LEVEL_SECURITY: WARN
      LOG_LEVEL_WEB: WARN
      LOG_LEVEL_SQL: WARN
      LOG_LEVEL_SQL_PARAMS: WARN

      # Management Configuration
      MANAGEMENT_ENDPOINTS: health,info,metrics
      MANAGEMENT_HEALTH_SHOW_DETAILS: when-authorized
      MANAGEMENT_HEALTH_PROBES: true
      MANAGEMENT_HEALTH_READINESS: true
      MANAGEMENT_HEALTH_LIVENESS: true

      # JVM Options
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseStringDeduplication"

    ports:
      - "8080:8080"
    volumes:
      - app_logs:/app/logs
    networks:
      - fundquest-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
  app_logs:
    driver: local

# Custom network
networks:
  fundquest-network:
    driver: bridge