server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: eureka-server
              uri: http://localhost:8761
              predicates:
                - Path=/eureka/**
          default-filters:
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Origin
                value: "*"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Methods
                value: "GET,POST,PUT,DELETE,OPTIONS"
            - name: AddResponseHeader
              args:
                name: Access-Control-Allow-Headers
                value: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway,refresh
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route: WARN
    org.springframework.cloud.gateway.filter: WARN
    com.netflix.discovery: INFO
    com.netflix.eureka: WARN
    ROOT: INFO